app/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'app.views.home', name='home'),
    # url(r'^signup-email/', 'app.views.signup_email'),
    # url(r'^email-sent/', 'app.views.validation_sent'),
        # url(r'^login/$', 'app.views.home'),
    url(r'^logout/$', 'app.views.logout', name='logout'),
    url(r'^done/$', 'app.views.done', name='done'),
    # url(r'^email/$', 'app.views.require_email', name='require_email'),
    #
    #
    # #url(r'^getvideourl_servicio/(?P<valor>.+)$', 'app.views.getvideourl_servicio', name='getvideourl_servicio'),
    # #
    url(r'^busqueda/$', 'app.views.busqueda', name='busqueda'),
    url(r'^company_details/(?P<id>.+)$', 'app.views.company_details', name='company_details'),
    # #url(r'^obten_busqueda/$', 'app.views.obten_busqueda', name='busqueda'),
    # #url(r'^obten_busqueda_servicio/$', 'app.views.obten_busqueda_servicio', name='busqueda'),
    # #
    url(r'^search_restaurants/$', 'app.views.search_restaurants', name='search_restaurants'),
    url(r'^search_points/$', 'app.views.search_points', name='search_points'),
    url(r'^search_companies/$', 'app.views.search_companies', name='search_companies'),
    url(r'^orders_view/$', 'app.views.orders_view', name='orders_view'),
    # url(r'^get_products/$', 'app.views.get_products', name='get_products'),
    # url(r'^search_simproduct_restaurants/$', 'app.views.search_simproduct_restaurants', name='search_simproduct_restaurants'),
    # #
    # #url(r'^obten_tags/(?P<tag>.+)$', 'app.views.obten_tags', name='obten_tags'),
    # #url(r'^register/$', 'app.views.register_form', name='register'),
    # #url(r'^restaurant_confirmacion/(?P<token>.+)$', 'app.views.restaurant_confirmacion', name='restaurant_confirmacion'),
    url(r'^detail/(?P<id>.+)$', 'app.views.detail', name='detail'),
    #
    url(r'^experiencia/$', 'app.views.experiencia', name='experiencia'),
    # #url(r'^restaurant_delivery/$', 'app.views.restaurant_delivery', name='restaurant_delivery'),
    url(r'^buyings/$', 'app.views.buyings', name='buyings'),
    url(r'^delete_order/$', 'app.views.delete_order', name='delete_order'),
    url(r'^order_service/$', 'app.views.order_service', name='order_service'),
    url(r'^guia/$', 'app.views.guia', name='guia'),
    url(r'^ayuda/$', 'app.views.ayuda', name='ayuda'),
    url(r'^addto_car/(?P<id>.+)$', 'app.views.addto_car', name='addto_car'),
    url(r'^check_availability/(?P<id>.+)$', 'app.views.check_availability', name='check_availability'),
    # url(r'^restaurant_update_status/(?P<restaurant_id>.+)/(?P<restaurant_status>.+)$', 'app.views.restaurant_update_status', name='restaurant_update_status'),
    # url(r'^save_list/', 'app.views.save_list', name='save_list'),
    # url(r'^restaurant_delivery_service/', 'app.views.restaurant_delivery_service', name='restaurant_delivery_service')
)

client_admin/urls.py
from django.conf.urls import patterns, url
from client_admin.views import *

urlpatterns = patterns('',
    # url(r'^$', rest_form, name='rest_form'),
    # url(r'local_form/$', local_form, name='local_form'),
    url(r'point_load/$', 'client_admin.views.point_load', name='point_load'),
    # url(r'product_form/$', product_form, name='product_form'),
    url(r'create_point/$', 'client_admin.views.create_point', name='create_point'),
    url(r'manage_orders/$', 'client_admin.views.manage_orders', name='manage_orders'),
    url(r'login/$', 'client_admin.views.login', name='login'),
    url(r'add_point/$', 'client_admin.views.add_point', name='add_point'),
    url(r'order_response/$', 'client_admin.views.order_response', name='order_response'),
    # url(r'popup/$', 'client_admin.views.popup', name='popup'),
    url(r'^add/(?P<model_name>\w+)/?$', 'tekextensions.views.add_new_model'),
    # url(r'add/^(?P<model_name>.+)$', 'client_admin.views.add_new_model', name='add'),
    url(r'^(?P<id>.+)$', dashboard, name='dashboard'),

)

kunfood/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


admin.autodiscover()
urlpatterns = patterns('',
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'^systemadmin/', include(admin.site.urls)),
#    url(r'^superadmin/', include('kunfood_admin.urls', namespace='kunfood_admin')),
    url(r'^admin/', include('client_admin.urls', namespace='client_admin')),
    url(r'^login/', 'client_admin.views.login'),
    # url(r'^add/(?P<model_name>\w+)/?$', 'tekextensions.views.add_new_model'),
    url(r'', include('app.urls')),
)

client_admin/models.py
from django.db import models

# Create your models here.

client_admin/forms.py
from django import forms
from django.db.models import Model
from django.forms import ModelForm
# from app.models import RestaurantRequest, Restaurant, Local, Product, Category
from app.models import Point
from tekextensions.widgets import SelectWithPopUp

class CustomForm(forms.Form):
    points = forms.ModelChoiceField(Point.objects, widget=SelectWithPopUp)
# class RestaurantForm(ModelForm):
#     class Meta:
#         model = Restaurant
#         fields = ['email', 'name', 'phone', 'address', 'website', ]
#
#
# class LocalForm(ModelForm):
#     class Meta:
#         model = Local
#         fields = ['id', 'name', 'phone', 'address', 'city', 'district', 'street', 'restaurant']
#
#
# class ProductForm(ModelForm):
#     class Meta:
#         model = Product
#         fields = ['name', 'category', ]
class PointForm(ModelForm):
    class Meta:
        model = Point
        fields = ['id', 'address', 'city', 'latitude', 'length', 'high', 'width', 'state','description','provider']


# class CustomForm(forms.Form):
#     selectfield = forms.ModelChoiceField(Model.objects, widget=SelectWithPopUp)

client_admin/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth import user_logged_in, login as auth_login, authenticate
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponseNotFound, HttpResponse
from django.utils.html import escape
from django.forms.models import modelform_factory
from django.db.models.loading import get_models, get_app, get_apps
from app.models import User, Order, OrderDetail, TypePoint, Point, Type, UserHasCompany
from django.contrib.auth.models import User as auth_User
from client_admin import forms
from client_admin.forms import PointForm


def login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        # user = auth_User.objects.get(email=email, password= password)
        auth_user = authenticate(username = password, password= password)
        # user_object = User.objects.filter(user__email=email, user__username=password)
        if auth_user:
            request.session['user'] = email
            auth_login(request, auth_user)
            if request.GET.get('next', False):
                return HttpResponseRedirect(request.GET.get('next'))
            else:
                return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)
        else:
            return render(request, 'login.html')
    else:
        return render(request, 'login.html')

@login_required
def dashboard(request, id):
    user = User.objects.get(user= request.user)
    order_objects = Order.objects.all()
    mlist = list()
    for m in order_objects:
        if user.id == m.provider.id:
            detail = OrderDetail.objects.get(pk=m.id)
            mlist.append({'point':detail.type_point.point.address, 'state':m.state})
    size = mlist.__len__()
    context = {
        'user': user,
        'orders': mlist,
        'size':size
    }
    return render(request, 'dashboard.html', context)

@login_required
def manage_orders(request):
    user = User.objects.get(user__id=request.user.id)
    order_objects = OrderDetail.objects.filter(order__provider__user=user)
    context = {
        'orders': order_objects
    }
    return render(request, 'manage_orders.html', context)

@login_required
def order_response(request):
    user = User.objects.get(user__id=id)
    user = User.objects.get(user__id=request.user.id)
    order_objects = OrderDetail.objects.filter(order__provider__user=user)
    context = {
        'orders': order_objects
    }
    return render(request, 'manage_orders.html', context)

@login_required
def create_point(request):
    user = User.objects.get(user__id=request.user.id)
    typepoints_objects = TypePoint.objects.filter(company__user__user=user)
    orders = list()
    for m in typepoints_objects:
        if not orders.__contains__('m.address'):
            temp_objects = OrderDetail.objects.filter(order__provider=user,type_point__point=m.point)
            # if temp_objects.__len__() != 0:
            orders.append({'id':m.point.id,'image':m.point.description,'type': m.type.name, 'address':m.point.address,'num_orders':temp_objects.__len__()})

    context = {
        'points': typepoints_objects,
        'orders': orders
    }
    return render(request, 'create_point.html', context)

@login_required
def add_point(request):
    user = User.objects.get(user__id=request.user.id)
    points_objects = Point.objects.all()
    types_objects = Type.objects.all()
    companies_objects = UserHasCompany.objects.filter(user = user)
    context = {
        'points': points_objects,
        'companies': companies_objects,
        'types':types_objects
    }
    return render(request, 'add_point.html', context)

#
# def rest_form(request):
#     if request.method == 'POST':
#         form = RestaurantForm(request.POST or None)
#         if form.is_valid():
#             pass
#     else:
#         restaurant = Restaurant.objects.get(pk=1)
#         form = RestaurantForm(instance=restaurant)
#
#     context = {
#         'form': form,
#         'restaurant': restaurant,
#     }
#
#     return render(request, 'client_admin/rest_form.html', context)
#
#
# def local_form(request):
#     restaurant = Restaurant.objects.get(pk=1)
#     if request.method == 'POST':
#         pk = request.POST.get('id')
#         if pk:
#             form = LocalForm(request.POST, instance=Local.objects.get(pk=pk))
#         else:
#             form = LocalForm(request.POST or None)
#         if form.is_valid():
#             form.save()
#     else:
#         form = LocalForm()
#
#     locals = Local.objects.filter(restaurant=restaurant)
#
#     #districts = District.objects.all();
#
#     context = {
#         'form': form,
#         'locals': locals,
#         'restaurant': restaurant,
#         'is_new': True,
#     }
#     return render(request, 'client_admin/form_local.html', context)
#
#
@login_required
def popup(request):
    return render(request, 'popup.html')

@login_required
def point_load(request):
    if request.method != 'POST':
        return redirect('client_admin:create_point')
    id = request.POST.get('id')
    point = Point.objects.filter(id=id)
    form = TypePoint.objects.filter(company__user__user=request.user, point=point)#Manejar session
    context = {
        'points':form,
        'orders':form
    }
    return render(request, 'create_point.html', context)

    # local = Local.objects.get(pk=id)
    # form = LocalForm(instance=local)
    #
    # locals = Local.objects.filter(restaurant=restaurant)

    # context = {
    #     # 'form': form,
    #     # 'locals': locals,
    #     # 'restaurant': restaurant,
    # }
    #
    # return render(request, 'create_point.html', context)

#
# def product_form(request):
#     categories = Category.objects.all()
#     restaurant = Restaurant.objects.get(pk=1)
#     if request.method == 'POST':
#         form = ProductForm(request.POST or None)
#         if form.is_valid():
#             product = form.save(commit=False)
#             product.restaurant = restaurant
#             product.save()
#     else:
#         form = ProductForm()
#
#     context = {
#         'form': form,
#         'categories': categories,
#         'products': Product.objects.all
#     }
#     return render(request, 'client_admin/form_product.html', context)
#
#
# context_processors.py
from django.conf import settings

def admin_media_prefix(request):
    return {'ADMIN_MEDIA_PREFIX': settings.ADMIN_MEDIA_PREFIX }

@login_required
def add_new_model(request, model_name):
    if (model_name.lower() == model_name):
        normal_model_name = model_name.capitalize()
    else:
        normal_model_name = model_name

    app_list = get_apps()
    for app in app_list:
        for model in get_models(app):
            if model.__name__ == normal_model_name:
                form = modelform_factory(model)

                if request.method == 'POST':
                    form = form(request.POST)
                    if form.is_valid():
                        try:
                            new_obj = form.save()
                        except forms.ValidationError, error:
                            new_obj = None

                        if new_obj:
                            return HttpResponse('<script type="text/javascript">opener.dismissAddAnotherPopup(window, "%s", "%s");</script>' % \
                                (escape(new_obj._get_pk_val()), escape(new_obj)))

                else:
                    form = form()

                page_context = {'form': form, 'field': normal_model_name}
                return render_to_response('popup.html', page_context, context_instance=RequestContext(request))

client_admin/templates/add_point.html
{% extends 'client_admin/../dashboard.html' %}
{% load url from future %}

{% block  content %}
    <!-- sidebar -->
       <div id="sidebar-nav">
        <ul id="dashboard-menu">
            <li >
                <a href="{% url 'client_admin:manage_orders' %}">
                    <i class="icon-picture"></i>
                    <span>Administrar Solicitudes(Ordenes)</span>
                </a>
            </li>
            <li class = "active">
                <div class="pointer">
                    <div class="arrow"></div>
                    <div class="arrow_border"></div>
                </div>
                <a href="{% url 'client_admin:create_point' %}">
                    <i class="icon-th-large"></i>
                    <span>Crear Punto publicitario</span>
                </a>
            </li>
            <li>

                <a href="../add/Point" onclick="return SelectWithPopUp(this)">
                    <i class="icon-code-fork"></i>
                    <span>Agregar Punto publicitario</span>
                </a>
            </li>

        </ul>
    </div>
    <!-- end sidebar -->


    <!-- main container -->
  <div class="content">

        <div class="row">
            <div class="col-md-6">
                <div id="pad-wrapper" class="form-page">
                    <div class="row form-wrapper">
                        <!-- left column -->
                        <div class="col-md-12 column">
                            <form action="client_admin/local_form/" method="post">
                                <input type="hidden" name="id" />
                                <input type="hidden" name="restaurant" />

                                <div class="field-box">
                                    <label>Punto:</label>

                                    <div class="col-md-9">
                                        <select name= "points" id="points" class="form-control inline-input"
                                                >
                                        {% for point in points %}
                                            <option value="{{ point.address }}" >{{ point.address }}</option>
                                        {% endfor %}
                                        </select>

                                        <a href="javascript:popup('../add/Point',400,600)" class="add-another" id="add_id_point" onclick="return showAddAnotherPopup(this);"> <img src="/static/admin/img/icon_addlink.gif" width="10" height="10" alt="Add Another"/></a>
                                    </div>
                                </div>
                                <div class="field-box">
                                    <label>Empresa:</label>

                                    <div class="col-md-9">
                                        <select class="form-control inline-input"
                                                >
                                        {% for company in companies %}
                                            <option value="{{ company.commercial_name }}">{{ company.commercial_name }}</option>
                                        {% endfor %}
                                        </select>
                                    <a href="javascript:popup('../add/UserHasCompany',400,300)" class="add-another" id="add_id_point" onclick="return showAddAnotherPopup(this);"> <img src="/static/admin/img/icon_addlink.gif" width="10" height="10" alt="Add Another"/></a>

                                    </div>
                                </div>

                                <div class="field-box">
                                    <label>Tipo de anuncio:</label>

                                    <div class="col-md-9">
                                         <select class="form-control inline-input"
                                                >
                                        {% for type in types %}
                                            <option value="{{ type.name }}">{{ type.name }}</option>
                                        {% endfor %}
                                        </select>


                                    <a href="../add/Type" class="add-another" id="add_id_point" onclick="return showAddAnotherPopup(this);"> <img src="/static/admin/img/icon_addlink.gif" width="10" height="10" alt="Add Another"/></a>



                                    </div>
                                </div>

                                <div class="field-box">
                                    <label>Precio:</label>

                                    <div class="col-md-9">
                                        <input class="form-control inline-input" placeholder="Cantidad en nuevos soles"
                                               type="text" name="phone">
                                    </div>
                                </div>

                                <div class="field-box">
                                    <label>Estado:</label>

                                    <div class="col-md-9">
                                         <select class="form-control inline-input"
                                                >
                                            <option >Disponible</option>
                                            <option >Ocupado</option>
                                            <option >Construccion</option>
                                        </select>

                                    </div>
                                </div>

                                <div id="map_canvas" style="width: 100%; height: 300px;"></div>

                                <br/>
                                <input type="submit" class="btn-glow primary"
                                       value="{% if is_new %}
                                        nuevo{% else %}Actualizar{% endif %}">
                            </form>
                        </div>
                    </div>
                </div>
            <a href="{% url 'client_admin:add_point' %}" class="btn-flat success pull-right"><span>+</span>
                            Agregar Punto</a>
            </div>

            <div class="col-md-6" style="border-left: 1px dashed #333">

                <div id="pad-wrapper" class="user-profile">
                    {% if is_new == False or not is_new %}
                        <a href="{% url 'client_admin:login' %}" class="btn-flat success pull-right"><span>+</span>
                            Agregar Punto</a>
                    {% endif %}
                    <div class="row header">
                        <div class="col-md-8">
                            <h3 class="name">Nuevo Punto >> {{ form.address }}</h3>
                        </div>
                    </div>
                </div>

                <div id="pad-wrapper" class="form-page">
                    <div class="row form-wrapper">
                        <!-- left column -->
                        <div class="col-md-12 column">
                            <form action="" method="post">
                                <div id="map_canvas" style="width: 100%; height: 500px;"></div>
                                <br/>
                                <input type="submit" class="btn-glow primary"
                                       value="{% if is_new %}Guardar nuevo{% else %}Actualizar{% endif %}">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <form id="form_aux" action="{% url 'client_admin:point_load' %}" method="post">
        <input type="hidden" name="id" id="id"/>
    </form>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="static/client_admin/js/jquery.dataTables.js"></script>
    <script type="text/javascript"
            src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <script src="{{ ADMIN_MEDIA_PREFIX }}js/admin/RelatedObjectLookups.js"></script>

    <script type="text/javascript">
    function popup(url,ancho,alto) {
    var posicion_x;
    var posicion_y;
    posicion_x=(screen.width/2)-(ancho/2);
    posicion_y=(screen.height/2)-(alto/2);
    window.open(url, "leonpurpura.com", "width="+ancho+",height="+alto+",menubar=0,toolbar=0,directories=0,scrollbars=no,resizable=no,left="+posicion_x+",top="+posicion_y+"");
    }
    </script>

    <script>

        var geocoder;
        var map;
        $(document).ready(function() {
            $('#points').change(function(event){
            //alert("Click event on Select has occurred!");
            $("option:selected", $(this)).each(function(){
                var obj = document.getElementById('points').value;
                var list=map.markers.getMarkers();
                alert("selected value"+obj+list[0].title);
                });
            });

        });
        function renderonmap(title) {
            var list = getMarkers();
            var numMarkers = map.getMarkers().length;
            for (var i=0; i< numMarkers; i++){
                if (list[i].title == title)
                    map.center(list[i].title);
            }
        }

        $(function () {
            map = new google.maps.Map(document.getElementById("map_canvas"));
            $('#locals').dataTable({
                "sPaginationType": "full_numbers"
            });
        });

        $('#locals tbody tr').click(function (e) {
            id = $(e.target).parent().attr('id');
            $('#form_aux #id').val(id);
            $('#form_aux').submit();
        });

        function initialize() {
            {% for m in points %}
                putmarker('{{ m.address }}','{{ m.latitude }}','{{ m.length}}');
                updateCenter('{{ m.latitude }}','{{ m.length}}');
            {% endfor %}

        }
        function putmarker(name, lat, lng) {
            var myLatlng = new google.maps.LatLng(lat, lng);
            var marker = new google.maps.Marker({
                position: myLatlng,
                title: name,
                animation: google.maps.Animation.DROP
            });
            marker.setMap(map);
        }
        function updateCenter(lat, lng) {
            var mapOptions = {
                center: new google.maps.LatLng(lat, lng),
                zoom: 16,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            map.setOptions(mapOptions);
        }
     google.maps.event.addDomListener(window, 'load', initialize);
    google.maps.event.addListener(map, 'click', function(event) {
                marker.setMap(null);
                marker = new google.maps.Marker({
                    map:       map,
                    position:  event.latLng
                });
            });
    </script>
{% endblock %}

client_admin/templates/create_point.html
{% extends 'client_admin/../dashboard.html' %}
{% load url from future %}
{% block  content %}
    <!-- sidebar -->
    <div id="sidebar-nav">
        <ul id="dashboard-menu">
            <li >
                <a href="{% url 'client_admin:manage_orders' %}">
                    <i class="icon-picture"></i>
                    <span>Administrar Solicitudes(Ordenes)</span>
                </a>
            </li>
            <li class = "active">
                <div class="pointer">
                    <div class="arrow"></div>
                    <div class="arrow_border"></div>
                </div>
                <a href="{% url 'client_admin:create_point' %}">
                    <i class="icon-th-large"></i>
                    <span>Crear Punto publicitario</span>
                </a>
            </li>
            <li>

                <a href="{% url 'client_admin:manage_orders' %}">
                    <i class="icon-code-fork"></i>
                    <span>Agregar Informacion al PP</span>
                </a>
            </li>

        </ul>
    </div>
    <!-- end sidebar -->


    <!-- main container -->
  <div class="content">

        <div class="row">
            <div class="col-md-6">
                <div id="pad-wrapper" class="users-list">
                    <h3>PUNTOS</h3>
                    <table class="table table-hover" id="locals">
                        <thead>
                        <tr>
                            <th class="col-md-4 sortable">
                                Imagen
                            </th>
                            <th class="col-md-4 sortable">
                                Ubicación
                            </th>
                            <th class="col-md-4 sortable">
                                Editar
                            </th>
                            <th class="col-md-4 sortable">
                                Solicitudes
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for point in orders %}
                            <tr id="{{ point.id }}" class="first">
                                <td>
                                    {{ point.image }}
                                    {{ point.price }}
                                </td>
                                <td>
                                    {{ point.address }}
                                    {{ point.state }}
                                </td>
                                <td>
                                    {{ point.type }}
                                </td>
                                <td>
                                    {{ point.num_orders }}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            <a href="{% url 'client_admin:add_point' %}" class="btn-flat success pull-right"><span>+</span>
                            Agregar Punto</a>
            </div>

            <div class="col-md-6" style="border-left: 1px dashed #333">

                <div id="pad-wrapper" class="user-profile">
                    {% if is_new == False or not is_new %}
                        <a href="{% url 'client_admin:login' %}" class="btn-flat success pull-right"><span>+</span>
                            Agregar Punto</a>
                    {% endif %}
                    <div class="row header">
                        <div class="col-md-8">
                            <h3 class="name">Nuevo Punto >> {{ form.address }}</h3>
                        </div>
                    </div>
                </div>

                <div id="pad-wrapper" class="form-page">
                    <div class="row form-wrapper">
                        <!-- left column -->
                        <div class="col-md-12 column">
                            <form action="" method="post">
                                <div id="map_canvas" style="width: 100%; height: 500px;"></div>
                                <br/>
                                <input type="submit" class="btn-glow primary"
                                       value="{% if is_new %}Guardar nuevo{% else %}Actualizar{% endif %}">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <form id="form_aux" action="{% url 'client_admin:point_load' %}" method="post">
        <input type="hidden" name="id" id="id"/>
    </form>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="static/client_admin/js/jquery.dataTables.js"></script>
    <script type="text/javascript"
            src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <script>
        var geocoder;
        var map;

        $(function () {
            map = new google.maps.Map(document.getElementById("map_canvas"));
            $('#locals').dataTable({
                "sPaginationType": "full_numbers"
            });
        });

        $('#locals tbody tr').click(function (e) {
            id = $(e.target).parent().attr('id');
            $('#form_aux #id').val(id);
            $('#form_aux').submit();
        });

        function initialize() {
            {% for m in points %}
                putmarker('{{ m.point.address }}','{{ m.point.latitude }}','{{ m.point.length}}');
                updateCenter('{{ m.point.latitude }}','{{ m.point.length}}');
            {% endfor %}

        }
        function putmarker(name, lat, lng) {
            var myLatlng = new google.maps.LatLng(lat, lng);
            var marker = new google.maps.Marker({
                position: myLatlng,
                title: name,
                animation: google.maps.Animation.DROP
            });
            marker.setMap(map);
        }
        function updateCenter(lat, lng) {
            var mapOptions = {
                center: new google.maps.LatLng(lat, lng),
                zoom: 16,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            map.setOptions(mapOptions);
        }
     google.maps.event.addDomListener(window, 'load', initialize);
    google.maps.event.addListener(map, 'click', function(event) {
                marker.setMap(null);
                marker = new google.maps.Marker({
                    map:       map,
                    position:  event.latLng
                });
            });
    </script>
{% endblock %}

client_admin/templates/formpopup.html
<a
    href="/add/{{ model }}/"
    class="add-another"
    id="add_id_{{ field }}"
    onclick="return showAddAnotherPopup(this);">
+
</a>